### ISSUE TITLE
.twig files seen as text files

### ISSUE THREAD

**Issue by marthesselink** [Athorcis/brackets-git#6]
I'm having this problem where my .twig files are seen as Text files. 

**What I did/tried:**

1. Uninstall brackets-twig.
2. Reload + Restart Brackets.
3. Set .twig as HTML files.
4. Download and install brackets-twig (version 1.1.2).
5. Open a Twig file (which is seen as an HTML file).
6. Set it to Twig.
7. Set as Default for .twig files.
8. Reload Brackets or restart and my .twig files are opened as Text files. 

This happens everytime I try it and I can't figure out why.

**Comment by Athorcis** [comment]
I've just published a new version with a quick fix for this bug, but there is clearly some odd behavior from Brackets i've opened an issue https://github.com/adobe/brackets/issues/12970
