### ISSUE TITLE
No Twig syntax highlight in updated Brackets

### ISSUE THREAD

**Issue by iTechCydia** [Athorcis/brackets-git#8]
Hi,

Your extension doesn't seem to work with the latest Brackets version. Are you planning to update it or something ? 

Thanks

**Comment by Athorcis** [comment]
Hi,

I'm not able to reproduce your problem with a fresh install of Brackets 1.12 under Windows 7.
Can you provide specific details about the problem ?

Which OS are you running ?
If you open the developer tools (F12) console, is there any errors relative to the extension ?

**Comment by iTechCydia** [comment]
Hi,

I'm using Brackets 1.12 under macOS 10.13.3. There is a screen capture of the developer tools console: 
![capture d ecran 2018-01-31 a 09 47 09](https://user-images.githubusercontent.com/15326311/35613345-1a8326a8-066c-11e8-87e1-f711a7a1546b.jpg)

**Comment by iTechCydia** [comment]
Ok I found the problem. The selected langage for my .twig file was HTML by default so no syntax highlight for Twig. See the "Cannot register file extension "twig" for Twig, it is already belongs to HTML" warning.
